# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.org }}:{{ template "iamPolicyController.leaderElectionRoleBinding" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "iamPolicyController.fullname" . }}
    chart: {{ template "iamPolicyController.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.org }}:{{ template "iamPolicyController.leaderElectionRole" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "iamPolicyController.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
