# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "iamPolicyController.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "iamPolicyController.fullname" . }}
    chart: {{ template "iamPolicyController.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.global.imagePullSecret }}
imagePullSecrets:
- name: {{ .Values.global.imagePullSecret }}
{{- end }}
