# Copyright Contributors to the Open Cluster Management project

fullnameOverride: null
nameOverride: null

org: open-cluster-management
replicas: 1
args:
  frequency: 30
  verbosity: 0

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources:
  requests:
    memory: "150Mi"
  limits:
    memory: "300Mi"

affinity: {}

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node.kubernetes.io/not-ready
  operator: Exists
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

clusterName: null
clusterNamespace: null

global:
  imagePullPolicy: Always
  imagePullSecret: null
  imageOverrides:
    iam_policy_controller: quay.io/open-cluster-management/iam-policy-controller:latest-2.5
  nodeSelector: {}
  proxyConfig: {}
