# Copyright Contributors to the Open Cluster Management project

fullnameOverride: null
nameOverride: null

org: open-cluster-management
replicas: 1

hubKubeConfigSecret: config-policy-controller-hub-kubeconfig

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 512Mi

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

clusterName: null

global: 
  imagePullPolicy: IfNotPresent
  imagePullSecret: open-cluster-management-image-pull-credentials
  imageOverrides: 
    config_policy_controller: quay.io/open-cluster-management/config-policy-controller:edge
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
