# Copyright Contributors to the Open Cluster Management project

fullnameOverride: null
nameOverride: null

org: open-cluster-management
replicas: 1
args:
  logLevel: 0
  pkgLogLevel: -1
  logEncoder: console
  evaluationConcurrency: 2
  clientQPS: 30
  clientBurst: 45
hubKubeConfigSecret: config-policy-controller-hub-kubeconfig

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 512Mi

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

clusterName: null
managedKubeConfigSecret: null

# This is the Kubernetes distribution of the managed cluster. If set to OpenShift,
# some features such as automatic TLS certificate generation will be used.
# kubernetesDistribution: OpenShift

# This will expose metrics over HTTP if it's not an OpenShift cluster.
prometheus:
  # This will be automatically enabled if it's an OpenShift cluster.
  enabled: false
  serviceMonitor:
    # This will be automatically set to openshift-monitoring if it's an OpenShift cluster.
    namespace: null

global: 
  imagePullPolicy: IfNotPresent
  imagePullSecret: open-cluster-management-image-pull-credentials
  imageOverrides: 
    config_policy_controller: quay.io/open-cluster-management/config-policy-controller:latest
    kube_rbac_proxy: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.10
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
